apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-questions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-questions
  template:
    metadata:
      labels:
        app: backend-questions
    spec:
      containers:
      - name: backend-questions
        image: backend-questions:latest
        imagePullPolicy: IfNotPresent # Ideal para Docker Desktop
        ports:
          - containerPort: 8000
        env:
          # Constrói a URL de conexão com o banco a partir dos secrets
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: POSTGRES_PASSWORD
          - name: DATABASE_URL
            value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/questoesdb"

          # Puxa as demais credenciais e chaves do secret da aplicação
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: GEMINI_API_KEY
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ADMIN_USERNAME
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ADMIN_PASSWORD
          - name: USER_USERNAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: USER_USERNAME
          - name: USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: USER_PASSWORD
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET_KEY
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://tempo.monitoring.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-questions-service
  labels:
    app: backend-questions
spec:
  selector:
    app: backend-questions
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000