apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-questions
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: backend-questions
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
