log_format proxy_format '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        'upstream_addr=$upstream_addr '
                        'upstream_status=$upstream_status '
                        'upstream_response_time=$upstream_response_time '
                        'request_time=$request_time';

upstream backend {
    server backend-questions-service.default.svc.cluster.local:8000;
}

server {
    listen 80;
    server_name localhost;

    access_log /var/log/nginx/access.log proxy_format;
    error_log /var/log/nginx/error.log info;

    root /usr/share/nginx/html;
    index index.html;

    location /api/generate {
        proxy_pass http://backend/generate;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        # Streaming (NDJSON)
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding on;
    }

    location /api/ {
        proxy_pass http://backend/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    location / {
        try_files $uri /index.html;
    }
}
